import { useEffect, useState } from 'react'
import { profile } from './data/profile'
import { sectors, tools } from './data/experienceData'
import { locations } from './data/locations'
import { gallery } from './data/galleryData'
import { project } from './data/projectsData'

const nav = [['Inicio','inicio'],['Experiencia','experiencia'],['Ubicaciones','ubicaciones'],['Proyectos','proyectos'],['Galería','galeria'],['Contacto','contacto']]
const cvPath = `${import.meta.env.BASE_URL}cv.pdf`

function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span> }
function SectionTitle({ eyebrow, title, copy }) { return <div className="section-title"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div> }
function Placeholder({ label, className='' }) { return <div className={`placeholder ${className}`} role="img" aria-label={label}><span>▧</span><small>{label}</small></div> }

function Navbar() {
  const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false)
  useEffect(()=>{const fn=()=>setScrolled(scrollY>30); addEventListener('scroll',fn); return()=>removeEventListener('scroll',fn)},[])
  return <header className={`nav ${scrolled?'scrolled':''}`}><a className="brand" href="#inicio"><b>{profile.initials}</b><span>{profile.name}<small>Ingeniería de campo</small></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Abrir menú">{open?'×':'☰'}</button><nav className={open?'open':''} aria-label="Navegación principal">{nav.map(([n,id])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{n}</a>)}<a className="btn small" href={cvPath} download>Descargar CV ↧</a></nav></header>
}

function Hero(){return <section id="inicio" className="hero"><div className="hero-grid"><div className="hero-copy reveal"><span className="status"><i/> Disponible para proyectos técnicos y servicios de campo</span><p className="kicker">INGENIERÍA · CAMPO · MEDIA TENSIÓN</p><h1>Experiencia técnica donde la operación <em>no puede detenerse.</em></h1><p className="lead">Ingeniero mecánico de servicios con experiencia en trabajo de campo, pruebas eléctricas y puesta en marcha de equipos en ambientes industriales, marítimos y de infraestructura crítica.</p><div className="actions"><a className="btn" href="#experiencia">Ver experiencia →</a><a className="btn ghost" href={cvPath} download>Descargar CV</a><a className="text-link" href="#contacto">Contactarme</a></div><div className="hero-id"><span>01</span><div><b>{profile.name}</b><small>{profile.role}</small></div></div></div><div className="hero-visual reveal"><Placeholder label="Reemplazar con fotografía profesional de campo"/><div className="coordinates">18.6° N — 92.3° O<br/>UBICACIÓN APROXIMADA</div><div className="voltage">MEDIA TENSIÓN <b>MT</b></div></div></div><a className="scroll" href="#sectores">DESPLAZAR <span>↓</span></a></section>}

function SectorCards(){return <section id="sectores" className="section compact"><div className="sector-grid">{sectors.map((s,i)=><a href="#experiencia" className="sector-card reveal" key={s.id}><span className="sector-num">0{i+1}</span><Icon>{s.icon}</Icon><h3>{s.title}</h3><p>{s.activity}</p><span className="arrow">↗</span></a>)}</div></section>}

function Profile(){return <section className="section profile-section"><div><SectionTitle eyebrow="PERFIL PROFESIONAL" title="Trabajo de campo. Evidencia técnica. Resultados confiables."/><p className="profile-copy">Mi experiencia se ha desarrollado principalmente en campo, participando en actividades de servicio, revisión, pruebas y documentación técnica para equipos eléctricos e instalaciones industriales. Mi enfoque combina disciplina operativa, seguridad, precisión y capacidad de adaptación.</p></div><div className="value-grid">{[['⌁','Seguridad'],['⌖','Precisión'],['⌕','Diagnóstico'],['▤','Documentación']].map(([i,n])=><div key={n}><Icon>{i}</Icon><b>{n}</b><small>Principio de trabajo</small></div>)}</div></section>}

function Experience(){return <section id="experiencia" className="section"><SectionTitle eyebrow="EXPERIENCIA POR SECTORES" title="Adaptabilidad en entornos que exigen precisión." copy="Una visión general, editable y sin información operativa confidencial."/><div className="experience-grid">{sectors.map((s,i)=><article className="experience-card reveal" key={s.id}><Placeholder label={`Agregar fotografía de ${s.title.toLowerCase()}`}/><div className="card-body"><span className="tag">{s.title}</span><h3>{s.activity}</h3><p>{s.text}</p><dl><div><dt>Ubicación</dt><dd>{s.location}</dd></div><div><dt>Enfoque</dt><dd>Servicio técnico</dd></div></dl><a href="#galeria">Ver fotografías →</a></div></article>)}</div></section>}

function LocationMap(){const [selected,setSelected]=useState(locations[0]); const [group,setGroup]=useState('todos'); const shown=locations.filter(x=>group==='todos'||x.group===group); return <section id="ubicaciones" className="section map-section"><SectionTitle eyebrow="COBERTURA" title="Experiencia en territorio y costa fuera" copy="Representación visual aproximada. No contiene coordenadas operativas, rutas ni datos de clientes."/><div className="map-controls">{[['todos','Todas'],['tierra','En tierra'],['offshore','Costa fuera']].map(([id,n])=><button className={group===id?'active':''} onClick={()=>setGroup(id)} key={id}>{n}</button>)}</div><div className="map-wrap"><div className="map" aria-label="Mapa esquemático e interactivo de México"><div className="mexico-shape">MÉXICO</div>{shown.map((l,i)=><button key={l.name} className={`pin ${l.group} ${selected.name===l.name?'selected':''}`} style={{left:`${l.x}%`,top:`${l.y}%`}} onClick={()=>setSelected(l)} aria-label={`Ver ${l.name}`}><span>{i+1}</span></button>)}<div className="map-grid"/></div><aside className="location-card"><span className="tag">{selected.group==='offshore'?'COSTA FUERA · APROX.':'EXPERIENCIA EN TIERRA'}</span><small>{selected.state}</small><h3>{selected.name}</h3><dl><div><dt>Tipo</dt><dd>{selected.type}</dd></div><div><dt>Actividad</dt><dd>{selected.activity}</dd></div></dl><p>Selecciona otro marcador para consultar la referencia.</p></aside></div></section>}

function Gallery(){const [filter,setFilter]=useState('Todos'); const [activity,setActivity]=useState('Todas'); const [active,setActive]=useState(null); const filters=['Todos',...new Set(gallery.map(x=>x.sector))]; const activities=['Todas',...new Set(gallery.map(x=>x.activity))]; const items=gallery.filter(x=>(filter==='Todos'||x.sector===filter)&&(activity==='Todas'||x.activity===activity)); useEffect(()=>{const key=e=>{if(e.key==='Escape')setActive(null); if(active&&e.key==='ArrowRight')setActive(gallery[(gallery.findIndex(x=>x.id===active.id)+1)%gallery.length]); if(active&&e.key==='ArrowLeft')setActive(gallery[(gallery.findIndex(x=>x.id===active.id)-1+gallery.length)%gallery.length])}; addEventListener('keydown',key); return()=>removeEventListener('keydown',key)},[active]); return <section id="galeria" className="section"><SectionTitle eyebrow="REGISTRO VISUAL" title="Galería de campo" copy="Espacio preparado para incorporar evidencia fotográfica propia."/><div className="filters" aria-label="Filtros de galería">{filters.map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}<label>Actividad <select value={activity} onChange={e=>setActivity(e.target.value)}>{activities.map(a=><option key={a}>{a}</option>)}</select></label></div><div className="gallery-grid">{items.map(item=><button className={`gallery-item ${item.size}`} key={item.id} onClick={()=>setActive(item)}><Placeholder label={item.label}/><span><b>{item.sector}</b><small>{item.activity} · Ampliar ↗</small></span></button>)}</div>{active&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Vista ampliada" onClick={()=>setActive(null)}><button className="close" onClick={()=>setActive(null)} aria-label="Cerrar">×</button><div onClick={e=>e.stopPropagation()}><Placeholder label={active.label}/><p>{active.sector} · {active.activity}</p><small>Usa ← → para navegar y Esc para cerrar</small></div></div>}</section>}

function Process(){return <section className="section process"><SectionTitle eyebrow="PROCESO" title="Una forma de trabajo basada en método"/><div className="process-grid">{[['01','⌕','Revisar','Condiciones, alcance y documentación disponible.'],['02','⌁','Medir','Datos técnicos con orden y trazabilidad.'],['03','✓','Verificar','Contrastar resultados y condiciones de operación.'],['04','▤','Documentar y entregar','Convertir hallazgos en evidencia técnica clara.']].map(x=><article key={x[0]}><span>{x[0]}</span><Icon>{x[1]}</Icon><h3>{x[2]}</h3><p>{x[3]}</p></article>)}</div></section>}

function Projects(){return <section id="proyectos" className="section"><SectionTitle eyebrow="INGENIERÍA APLICADA" title="Proyectos y desarrollo técnico"/><article className="project"><div className="project-visual"><div className="blueprint"><span>MOTOR</span><i/><i/><i/></div><small>Agregar renders, diagramas o fotografías del prototipo</small></div><div className="project-copy"><span className="tag amber">{project.type}</span><h3>{project.title}</h3><p>{project.description}</p><div className="chips">{project.areas.map(a=><span key={a}>{a}</span>)}</div><a className="text-link" href="#contacto">Solicitar información →</a></div></article></section>}

function Tools(){return <section className="section tools"><SectionTitle eyebrow="CAPACIDADES" title="Software y herramientas" copy="Los nombres entre corchetes son campos pendientes de confirmar."/><div className="tools-grid">{tools.map((t,i)=><article key={t.title}><span>0{i+1}</span><h3>{t.title}</h3>{t.items.map(x=><p key={x}>{x}</p>)}</article>)}</div></section>}

function About(){return <section className="section about"><div className="about-photo"><Placeholder label="Agregar fotografía profesional"/></div><div><SectionTitle eyebrow="SOBRE MÍ" title={profile.name}/><p>Ingeniero mecánico orientado al servicio de campo y a la revisión técnica de equipos eléctricos. Capacidad para integrarse a distintos entornos industriales, documentar actividades y comunicar resultados con claridad.</p><div className="principles">{profile.principles.map(x=><span key={x}>✓ {x}</span>)}</div></div></section>}

function Contact(){return <section id="contacto" className="section contact"><div><span className="eyebrow">CONTACTO</span><h2>Conversemos sobre el próximo reto técnico.</h2><p>Disponible para proyectos de ingeniería, servicios de campo y oportunidades profesionales.</p></div><div className="contact-links"><a href={`mailto:${profile.email}`}><small>Correo</small><b>{profile.email}</b><span>↗</span></a><a href={profile.linkedin}><small>LinkedIn</small><b>{profile.linkedin}</b><span>↗</span></a><a href={cvPath} download><small>Currículum</small><b>Descargar CV</b><span>↓</span></a><p>Coloca el archivo definitivo en <code>/public/cv.pdf</code>.</p></div></section>}

function Footer(){return <footer><div className="brand"><b>{profile.initials}</b><span>{profile.name}<small>{profile.role}</small></span></div><p>Portafolio profesional de ingeniería y servicios de campo</p><small>La información presentada omite datos operativos y confidenciales. © {new Date().getFullYear()}</small></footer>}

export default function App(){return <><Navbar/><main><Hero/><SectorCards/><Profile/><Experience/><LocationMap/><Gallery/><Process/><Projects/><Tools/><About/><Contact/></main><Footer/></>}
